### ISSUE TITLE
mainnet node2 is no longer proposing blocks

### ISSUE THREAD

**Issue by dckc** [tgrospic/rnode-client-js#20]
I picked from the mainnet dropdown without really thinking about it and got node2.

@gsj5 reminds me that `node2` is no longer proposing blocks.

Let's take it out of the dropdown.

**Comment by tgrospic** [comment]
@dckc node2 is removed from the list. Thanks for reporting!

Here is also the ticket for node to return error is deploy is on read-only node.
https://github.com/rchain/rchain/issues/3266

**Comment by dckc** [comment]
I just picked node2 again. odd.

**Comment by tgrospic** [comment]
@dckc Are you mean on test net? On main net all validators are proposing blocks.

**Comment by dckc** [comment]
Right. It took about 20 minutes, but my transaction eventually went through
